# Use the official Python image as the base image
FROM python:3.10-bookworm  

# Set the working directory in the container
WORKDIR /app

# Copy the Python file into the container
COPY demo.py .

# Set the command to run the Python file
CMD ["python", "demo.py"]